### ISSUE TITLE
Declassamento — ToDo list

### ISSUE THREAD

**Issue by Armilio** [Armilio/ATC9_ACE#6]
- [x] Modifiche script per passare da una classe all'altra dopo ogni morte.
- [x] Creazioni nuovi classi "depotenziate" in InventoryLoadouts.hpp
- [x]  Creazioni nuovi classi "depotenziate" in LoadoutParams
- [x] Eliminare salvataggio equip? diventa inutile. 
- [x] Modifiche compatibilità sistema tickets.

## Progressione vite:

**AT specialist:**
titan---->metis--->RPG
titan ----> NLAW----> MAAWS

**Rifleman AT:**
RPG/Maaws-----> RPG/Maaws ----> RPG/maaws

**Carristi/piloti:**
Niente

**AA specialist:**
Niente

**Sniper:**
12,7 ------------> 7,62 -----------> 6,5

**Spotter:**
Default ----------> Niente GPS ----------> Niente lanciagranate & acog

**SF:**
Default ------------> Niente ACOG & lasci solo fucile d'assalto base ----------> Niente paracadute & silenziatori

**TL:**
Default --------------------> niente ACOG -------------------------> niente lanciagranate

**Mitragliere:**
Default --------------------> Niente acog/niente mg pesanti ---------------> solo autorifle leggeri, tipo MXL.

**Granatiere:**
Default --------------------> Niente ACOG ------------------------> niente lanciagranate

**Marksman:**
Default --------------------> Niente ottica da marksman --------------> fuciliere

**Rifleman**
Default (ACOG) ---------------> Default (acog) ---------- niente acog

**Comment by NikLoc** [comment]
Guardando un po' in giro, mi chiedevo se avevate testato/valutato le funzioni del saveInventory e loadInventory. Sono state implementate in arma 3 nelle versioni rispettive 0.58 e 1.00. Facendo dei test molto semplici mi è uscito:

`[["U_B_CombatUniform_mcam",["ACE_EarPlugs","ACE_fieldDressing","ACE_fieldDressing","ACE_morphine","20Rnd_762x51_Mag","20Rnd_762x51_Mag"]],["V_PlateCarrier1_rgr",["20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","20Rnd_762x51_Mag","16Rnd_9x21_Mag","16Rnd_9x21_Mag","SmokeShell","SmokeShellGreen","Chemlight_green","Chemlight_green","HandGrenade","HandGrenade"]],["",[]],"H_HelmetB","G_Aviator","Binocular",["srifle_DMR_03_tan_F",["","acc_pointer_IR","optic_AMS_snd","bipod_01_F_snd"],"20Rnd_762x51_Mag"],["",["","","",""],""],["hgun_P07_F",["","","",""],"16Rnd_9x21_Mag"],["ItemMap","ItemCompass","tf_microdagr","tf_anprc152_1","NVGoggles"],[]]`

Capisco che l'implementazione di tali funzioni richiederebbero un estensivo cambiamento però magari lavorando con qualcosa del genere potrebbe rivelarsi più semplice e stabile.

**Comment by NikLoc** [comment]
Pensandoci, è davvero necessario il salvataggio dell'equip? Uno magari dice "mi salvo le cose base" però alla fine se si passa da 6 vite a 3 con un cambiamento per ognuna, non mi pare nemmeno necessario il salvataggio. Nelle scorse ATC l'equipaggiamento rimaneva pressochè identico per cui risparmiava tempo il salvataggio, però adesso?

**Comment by Armilio** [comment]
Sì vero si può cancellare se si fa il declassamento, non avrebbe più senso.

**Comment by NikLoc** [comment]
Stavo controllando l'initialization order di arma: se noi la creazione dell' Array UID lo spostassimo in Pre-init quindi prima dell'inizializzazione di qualunque oggetto ed anche delle espressioni dentro l'editor, potremmo decidere quale loadout dare visto che le vite JIP o meno le sappiamo ancor prima dell'inizializzazione del player. Il problema è che non so se l' UID è possibile raccoglierlo tramite funzione in pre-init... logicamente potrei dire di si visto che i giocatori essendo in lobby sono già riconosciuti.

Comunque per inciso sto lavorando sul CfgRespawn e sono riuscito ad escludere le funzioni addGears, getBasicLoadout e SaveLoadout. I risultati sono promettenti visto che non serve tutto quel popo' di script per equipaggiare la gente.

**Comment by Armilio** [comment]
> Il problema è che non so se l' UID è possibile raccoglierlo tramite funzione in pre-init... 

Ho dubbi perché io i tickets li assegno così:

`{//Settare vite a init server/partita
	[_x,5,false] call BIS_fnc_respawnTickets; 
}foreach allUnits;`

e

`{//Riempire gli array con in memoria giocatori e vite.
	PUID = getPlayerUID _x;
	UIDArray pushBackUnique PUID; 
	UIDTicketsArray pushbackUnique [PUID, 5];
}foreach allUnits; `

Riconosce allUnits e sopratutto getPlayerUID nel pre-init? **da testare.**

> Comunque per inciso sto lavorando sul CfgRespawn e sono riuscito ad escludere le funzioni addGears, getBasicLoadout e SaveLoadout.

CfgRespawnInventory? buono, se vedi che funziona ricorda di aggiornare la branch ovviamente così posso vedere anche io.

**Comment by Armilio** [comment]
@NikLoc Ci stavo ragionando anche io sul pre-init, ma... i tickets sono una cosa che si dà in locale, è il valore il locale che vince su tutto, sarei sorpreso se funzionasse.

**Comment by NikLoc** [comment]
Ho testato il pre-init e come previsto non ha riconosciuto il Allplayers. 
Quindi ho iniziato a percorrere una strada diversa: non usare l'init dell'unità dentro l'editor che secondo me è il punto più critico dell' [Initialization order](https://community.bistudio.com/wiki/Initialization_Order)

Siccome l'aggiunta dell'equip viene fatta per esecuzione dell'init.sqf potremmo inserire l' initServer.sqf che non c'è e trasferire il tuo Ticket.sqf dentro questo. Si avrebbe la creazione dell' array prima perfino dell' initPlayerServer.sqf . 

Quindi in questo instante si avrebbe comunque il tempo di settare la classe in tutto comodo sfruttando qualcosa tipo il classname dell'unità (per quello tornerebbe utile la funzione, opportunamente modificata, che avevo fatto per definire la classe in base al nome nella lista dell'editor) o magari qualcos'altro che se ci penso scommetto che mi viene in mente.

Ho provato a mettere anche l' initPlayerLocal ed ho modificato la mia funzione in modo che mi restituisse la classe. Funziona per quello però che sia sicuro usarlo? Le robe in locale mi hanno sempre dato l'impressione di essere più facili da manipolare, vabbè che poi tanto la classe viene fatta solo all'inizio ed i ticket li fa il server per cui uno può anche cambiare slot per la classe ma perde comunque il livello.

Poi si deve riuscire a settare la classe uscita sull'unità del giocatore ed il gioco è fatto. In teoria se non ci sono intoppi dovrebbe essere tutto settato prima dell'avvento dell' init.sqf con il loadinventory.

Che dici? Potrebbe filare come cosa oppure c'è qualche problema di località?

**Comment by Armilio** [comment]
I tickets non sono del server, se sono individuali devono essere locali. Non c'è alternativa. A meno di non usare più i ticket e di usare semplicemente solo gli array UIDTicketsArray, ma non so come funzionerebbe.

**Comment by Armilio** [comment]
Allora, i tickets non si possono togliere completamente per un problema: che c'è il respawn. Per cui quando l'array raggiunge zero vite, uccidi il tizio in onplayerrespawn, ma quello respawna ancora e ancora e ancora. Quindi qualche sorta di tickets ci vuole, perché l'unico modo per far finire il ciclo. Detto questo posso rendere meno importanti i tickets e fargli fare riferimento quasi sempre all'array. 

Bisogna provare.

Sulla località, sono sicuro che almeno onPlayerRespawn è eseguito solo in locale. Altra rogna insomma di cui tenere conto.

**Comment by NikLoc** [comment]
Io non dico di rimuovere i ticket. Ma è necessario renderli il più possibile dipendenti dall' ArrayUID. Io nell'altro post ho detto di mettere il ticket.sqf dentro initServer.sqf senza guardarlo troppo. A me interessava solo creare l' arrayUID per poi in un secondo momento, magari già come è fatto adesso, in base ai risultati vengono dati i ticket e l'equip di conseguenza. Per cui mi correggo. Si potrebbe scorporare la creazione dell'array di UID da dov'è ora e metterlo nell' initServer.sqf e poi tutto il resto mi pare lineare. Locale o meno che siano i tickets non penso facciano differenza perchè il valore di riferimento si crea prima dell'esecuzione dell'attuale tickets.sqf, initplayerlocal ed initplayerserver. 

Poi per il resto il respawn va bene così com'è. Tranne per quel problema che la gente spawna una volta in più e deve essere uccisa manualmente.

Non ho guardato la parte JIP di questo processo, ma mi pareva l'avessi già coperta nell'initplayerserver?

**Comment by NikLoc** [comment]
Testato con Nemesi in dedicato e dopo diverse modifiche pare funzionare. Passato a lei per ulteriori test approfonditi su equip ed altre modifiche marginali per migliorare il sistema.
